# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최은호
title: 게임 클라이언트 프로그래머
email: eunho5751@naver.com
website: https://eunho5751.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  eunho5751
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  자기소개

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 셀빅
        link: https://cellbig.com
        # link_text: boringcompany.com
        sub_title: 클라이언트 프로그래머
        caption: 2022.12 ~ 2025.12
        quote: >
          Message 1
        description: | # this will include new lines to allow paragraphs
            Message 2

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
